- name: Create an internal network
  docker_network:
    name: "{{ net_name }}"
    driver: "bridge"
    internal: false
    ipam_config:
      - subnet: "{{ subnet }}"
        gateway: "{{ subnet | regex_replace('^(?P<addr>([0-9]{1,3}\\.){3})[0-9]{1,3}\/[0-9]{2}$', '\\g<addr>1') }}"
