version: '3'

services:

  reactive-kvs-unsafe:
    image: key-value-store:reactive-independent-0.0.1
    container_name: reactive-kvs-unsafe
    environment:
      - NODE_SERVICE_STRATEGY=Unsafe
    ports:
      - "8001:8080"
