version: '2'

services:

  etcd1:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
      - ETCDCTL_API=2
    volumes:
      - etcd_data:/bitnami/etcd
    ports: 
      - 8001:2379

volumes:
  etcd_data:
    driver: local
