version: '3'

services:

  reactive-kvs-unsafe:
    build: ../../reactive/key-value-store-independent
    image: key-value-store:reactive-independent
    container_name: reactive-kvs-unsafe
    environment:
      - NODE_SERVICE_STRATEGY=Unsafe
    ports:
      - "8001:8080"
