version: '3'

services:

  reactive-kvs-linearizable:
    build: ../../reactive/key-value-store-independent
    image: key-value-store-v2:reactive-independent
    container_name: reactive-kvs-linearizable
    environment:
      - NODE_SERVICE_STRATEGY=Publisher
    ports:
      - "8001:8080"
