- name: Create Raft Server Containers
  include_role:
    name: raft-server
  vars:
    server_number: "{{ item }}"
    server_addr: "10.0.0.{{ item }}"
  loop: "{{ range(1, (cluster_size + 1)) | list }}"

