- name: Create Raft Server Containers
  include_role:
    name: raft-server
  vars:
    server_number: "{{ item }}"
    server_addr: "{{ subnet | regex_replace('^(?P<addr>([0-9]{1,3}\\.){3})[0-9]{1,3}\/[0-9]{2}$', '\\g<addr>') + ((item + 10) | string) }}"
  loop: "{{ range(1, (cluster_size + 1)) | list }}"

