version: '3'

services:

  reactive-kvs-unsafe:
    build: ../reactive/key-value-store-independent
    image: key-value-store:reactive-independent-v5
    container_name: reactive-kvs-linearizable
    environment:
      - NODE_SERVICE_STRATEGY=Publisher
    ports:
      - "8001:8080"
