---
- name: Destroy Infrastructure
  hosts: localhost
  tasks:

    - name: Remove raft server containers
      docker_container:
        name: "raft-server-{{ item }}"
        state: absent
        container_default_behavior: compatibility
      loop: "{{ range(1, (cluster_size + 1))|list }}"

    - name: Delete docker image
      docker_image:
        name: "{{ docker_image_name }}"
        state: absent
        tag: latest
