---
- name: Build Raft Server Image
  hosts: localhost
  gather_facts: no
  roles:
    - raft-servlet-image

- name: Deploy Raft Cluster
  hosts: localhost
  gather_facts: no
  roles:
    - raft-cluster
