- name: Deploy Raft Server
  docker_container:
    name: "raft-server-{{ server_number }}"
    image: "{{ docker_image_name }}"
    container_default_behavior: compatibility
    env:
      RAFT_HOSTNAME: "{{ server_addr }}:8080"
      RAFT_CLUSTER: "{{ range(11, (cluster_size + 11)) | map('regex_replace', '(.+)', '10.0.0.\\1:8080') | join(',')}}"
      RAFT_ELECTION-TIMEOUT-MIN: "2000"
      RAFT_ELECTION-TIMEOUT-MAX: "3000"
      RAFT_HEARTBEEAT: "1000"
      RAFT_COMMUNICATION-STRATEGY: "REST"
      RAFT_STATE-MACHINE-STRATEGY: "INDEPENDENT"
    networks_cli_compatible: no
    networks:
      - name: "{{ net_name }}"
        ipv4_address: "{{ server_addr }}"
      #- name: db_net
    ports:
      - "{{ 8000 + server_number }}:8080"
      #- "{{ server_addr }}:8080:8080"
      #- ports for other networks
