name: Main-Build

on:
  push:
    branches:
      - main
      - reactive/refactor
  pull_request:
    branches:
      - main
      - reactive/refactor

jobs:

  servlet:

    name: Servlet
    
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-latest]
        java-version: [16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven - Package, Build, Test
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./servlet

  reactive:

    name: Reactive

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-latest]
        java-version: [16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven - Package, Build, Test
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./reactive
