name: Test-Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test-examples:

    name: Test Examples
    
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-latest]
        java-version: [15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      # Distributed Counter
      - name: Distributed Counter - Servlet Stack
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./test-examples/distributed-counter/servlet-stack
      - name: Distributed Counter - Reactive Stack
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./test-examples/distributed-counter/reactive-stack

      # Fault-Tolerant Distributed Counter
      - name: Fault-Tolerant Distributed Counter - Servlet Stack - Independent Config
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./test-examples/fault-tolerant-distributed-counter/servlet/independent
      #- name: Fault-Tolerant Distributed Counter - Servlet Stack - Embedded Config
        #run: mvn --batch-mode --update-snapshots verify
        #working-directory: ./test-examples/fault-tolerant-distributed-counter/servlet/embedded

      # Key-Value Store
      - name: Key-Value Store - Servlet Stack - Independent Config
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./test-examples/key-value-store/servlet/key-value-store-independent
      #- name: Key-Value Store - Servlet Stack - Embedded Config
       # run: mvn --batch-mode --update-snapshots verify
        #working-directory: ./test-examples/key-value-store/servlet/key-value-store-embedded

      # More examples must be here
      # ...
